[package]
name = "npins"
version = "0.2.4"
edition = "2021"
license = "EUPL-1.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
github-actions = []

[dependencies]
serde = { version = "^1.0", features = [ "derive" ] }
serde_json = { version = "^1.0", features = ["preserve_order"] }
url = { version = "^2.2.2", features = [ "serde" ] }
structopt = "^0.3"
anyhow = "^1.0"
tokio = { version = "^1.0", features = ["macros", "rt-multi-thread", "process"] }
env_logger = { version = "^0.10.0", features = ["color", "auto-color", "regex"], default-features = false }
log = "^0.4"
reqwest = { version = "0.11.7", features = [ "rustls-tls" ], default-features = false }
async-trait = "0.1.52"
lenient_semver_parser = { version = "0.4.2", default-features = false }
lenient_version = { version = "0.4.2" }

[dev-dependencies]
envtestkit = "1.1.2"
